name: Manage Labels

on:
  workflow_dispatch: # This ensures the workflow runs only when manually triggered

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Sync Labels
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const path = '.github/labels.json';
          const labels = JSON.parse(fs.readFileSync(path, 'utf8'));

          for (const label of labels) {
            try {
              const existingLabel = await github.rest.issues.getLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: label.name,
              });

              await github.rest.issues.updateLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: label.name,
                color: label.color,
                description: label.description,
              });
            } catch (error) {
              if (error.status === 404) {
                await github.rest.issues.createLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: label.name,
                  color: label.color,
                  description: label.description,
                });
              } else {
                throw error;
              }
            }
          }
