name: Manage Labels

on:
  workflow_dispatch: # This ensures the workflow runs only when manually triggered

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout

    - name: Sync Labels
      uses: actions/github-script
      with:
        script: |
          const script = require('./.github/scripts/sync-labels.js');
          script({ github, context });